export const squareMeasures = [
    { shortName: "м2", fullName: "Квадратные метры", size: 1 },
    { shortName: "см2", fullName: "Квадратные сантиметры", size: 1e-4 },
    { shortName: "дм2", fullName: "Квадратные дециметры", size: 1e-2 },
    { shortName: "км2", fullName: "Квадратные километры", size: 1e6 },
    { shortName: "мм2", fullName: "Квадратные миллиметры", size: 1e-6 },
    { shortName: "мкм2", fullName: "Квадратные микроны", size: 1e-12 },
    { shortName: "ha", fullName: "Гектары", size: 1e4 },
    { shortName: "a", fullName: "Ары", size: 1e2 },
    { shortName: "ac", fullName: "Акры", size: 4046.86 },
    { shortName: "миля2", fullName: "Квадратные мили", size: 2.59e6 },
    { shortName: "ярд2", fullName: "Квадратные ярды", size: 0.836127 },
    { shortName: "фут2", fullName: "Квадратные футы", size: 0.092903 },
    { shortName: "дюйм2", fullName: "Квадратные дюймы", size: 0.00064516 },
    { shortName: "rd2", fullName: "Квадратные перчи", size: 25.29 },
    { shortName: "qing", fullName: "Цин", size: 66667 },
    { shortName: "mu", fullName: "Му", size: 666.7 },
    { shortName: "chi2", fullName: "Квадратные чи", size: 0.1111111 },
    { shortName: "cun2", fullName: "Квадратные цунь", size: 0.00111111 }
];
