export const lengthMeasures = [
    { shortName: "км", fullName: "Километры", size: 1 },
    { shortName: "м", fullName: "Метры", size: 1 },
    { shortName: "дм", fullName: "Дециметры", size: 1 },
    { shortName: "см", fullName: "Сантиметры", size: 1 },
    { shortName: "мм", fullName: "Миллиметры", size: 1 },
    { shortName: "&#956;m", fullName: "Микрометры", size: 1 },
    { shortName: "нм", fullName: "Нанометры", size: 1 },
    { shortName: "пм", fullName: "Пикометры", size: 1 },
    { shortName: "nmi", fullName: "Морские мили", size: 1 },
    { shortName: "mi", fullName: "Мили", size: 1 },
    { shortName: "fur", fullName: "Фурлонги", size: 1 },
    { shortName: "ftm", fullName: "Морские сажени", size: 1 },
    { shortName: "ярд", fullName: "Ярды", size: 1 },
    { shortName: "ft", fullName: "Футы", size: 1 },
    { shortName: "in", fullName: "Дюймы", size: 1 },
    { shortName: "li", fullName: "Ли", size: 1 },
    { shortName: "zhang", fullName: "Чжан", size: 1 },
    { shortName: "chi", fullName: "Чи", size: 1 },
    { shortName: "cun", fullName: "Цунь", size: 1 },
    { shortName: "fen", fullName: "Фэнь", size: 1 },
    { shortName: "hao", fullName: "Хао", size: 1 },
    { shortName: "pc", fullName: "Парсек", size: 1 },
    { shortName: "ld", fullName: "Лунное расстояние", size: 1 },
    { shortName: "au", fullName: "Астрономическая единица", size: 1 },
    { shortName: "ly", fullName: "Световой год", size: 1 }
];
